### ISSUE TITLE
Construção REST Backend

### ISSUE THREAD

**Issue by joaolcaas** [MattheusB/vacina-virtual-backend#7]
Epic voltada para todas as atividades que focam na construção da API REST do sistema de vacinas

**Comment by LucasFOliveira** [comment]
Finished.

**Comment by LucasFOliveira** [comment]
Finished.

**Comment by LucasFOliveira** [comment]
Principais funções feitas, porém sem login implementado.

**Comment by LucasFOliveira** [comment]
Resolved!
